[package]
name = "gs-flux"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
converter_core = { path = "../converter_core" }
indicatif = "0.18.0"
