[package]
name = "converter_core"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
csv = "1.3.1"
flate2 = "1.1.2"
ply-rs = "0.1.3"
rayon = "1.11.0"
spz_rs = "0.1.0"
thiserror = { workspace = true}
