[package]
name = "wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
converter_core = { path = "../converter_core" }
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"
